# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: music_service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'music_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13music_service.proto\x12\x05music\"\x07\n\x05\x45mpty\"-\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\"0\n\x04Song\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06\x61rtist\x18\x03 \x01(\t\"$\n\x08Playlist\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"&\n\x08UserList\x12\x1a\n\x05users\x18\x01 \x03(\x0b\x32\x0b.music.User\"&\n\x08SongList\x12\x1a\n\x05songs\x18\x01 \x03(\x0b\x32\x0b.music.Song\"2\n\x0cPlaylistList\x12\"\n\tplaylists\x18\x01 \x03(\x0b\x32\x0f.music.Playlist\"\x14\n\x06UserId\x12\n\n\x02id\x18\x01 \x01(\x05\"\x18\n\nPlaylistId\x12\n\n\x02id\x18\x01 \x01(\x05\"\x14\n\x06SongId\x12\n\n\x02id\x18\x01 \x01(\x05\x32\x9e\x02\n\x0cMusicService\x12)\n\x08GetUsers\x12\x0c.music.Empty\x1a\x0f.music.UserList\x12)\n\x08GetSongs\x12\x0c.music.Empty\x1a\x0f.music.SongList\x12:\n\x14GetPlaylistsByUserId\x12\r.music.UserId\x1a\x13.music.PlaylistList\x12:\n\x14GetSongsFromPlaylist\x12\x11.music.PlaylistId\x1a\x0f.music.SongList\x12@\n\x1aGetPlaylistsContainingSong\x12\r.music.SongId\x1a\x13.music.PlaylistListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'music_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=30
  _globals['_EMPTY']._serialized_end=37
  _globals['_USER']._serialized_start=39
  _globals['_USER']._serialized_end=84
  _globals['_SONG']._serialized_start=86
  _globals['_SONG']._serialized_end=134
  _globals['_PLAYLIST']._serialized_start=136
  _globals['_PLAYLIST']._serialized_end=172
  _globals['_USERLIST']._serialized_start=174
  _globals['_USERLIST']._serialized_end=212
  _globals['_SONGLIST']._serialized_start=214
  _globals['_SONGLIST']._serialized_end=252
  _globals['_PLAYLISTLIST']._serialized_start=254
  _globals['_PLAYLISTLIST']._serialized_end=304
  _globals['_USERID']._serialized_start=306
  _globals['_USERID']._serialized_end=326
  _globals['_PLAYLISTID']._serialized_start=328
  _globals['_PLAYLISTID']._serialized_end=352
  _globals['_SONGID']._serialized_start=354
  _globals['_SONGID']._serialized_end=374
  _globals['_MUSICSERVICE']._serialized_start=377
  _globals['_MUSICSERVICE']._serialized_end=663
# @@protoc_insertion_point(module_scope)
