# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import music_service_pb2 as music__service__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in music_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MusicServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUsers = channel.unary_unary(
                '/music.MusicService/GetUsers',
                request_serializer=music__service__pb2.Empty.SerializeToString,
                response_deserializer=music__service__pb2.UserList.FromString,
                _registered_method=True)
        self.GetSongs = channel.unary_unary(
                '/music.MusicService/GetSongs',
                request_serializer=music__service__pb2.Empty.SerializeToString,
                response_deserializer=music__service__pb2.SongList.FromString,
                _registered_method=True)
        self.GetPlaylistsByUserId = channel.unary_unary(
                '/music.MusicService/GetPlaylistsByUserId',
                request_serializer=music__service__pb2.UserId.SerializeToString,
                response_deserializer=music__service__pb2.PlaylistList.FromString,
                _registered_method=True)
        self.GetSongsFromPlaylist = channel.unary_unary(
                '/music.MusicService/GetSongsFromPlaylist',
                request_serializer=music__service__pb2.PlaylistId.SerializeToString,
                response_deserializer=music__service__pb2.SongList.FromString,
                _registered_method=True)
        self.GetPlaylistsContainingSong = channel.unary_unary(
                '/music.MusicService/GetPlaylistsContainingSong',
                request_serializer=music__service__pb2.SongId.SerializeToString,
                response_deserializer=music__service__pb2.PlaylistList.FromString,
                _registered_method=True)


class MusicServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSongs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlaylistsByUserId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSongsFromPlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlaylistsContainingSong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MusicServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsers,
                    request_deserializer=music__service__pb2.Empty.FromString,
                    response_serializer=music__service__pb2.UserList.SerializeToString,
            ),
            'GetSongs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSongs,
                    request_deserializer=music__service__pb2.Empty.FromString,
                    response_serializer=music__service__pb2.SongList.SerializeToString,
            ),
            'GetPlaylistsByUserId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlaylistsByUserId,
                    request_deserializer=music__service__pb2.UserId.FromString,
                    response_serializer=music__service__pb2.PlaylistList.SerializeToString,
            ),
            'GetSongsFromPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSongsFromPlaylist,
                    request_deserializer=music__service__pb2.PlaylistId.FromString,
                    response_serializer=music__service__pb2.SongList.SerializeToString,
            ),
            'GetPlaylistsContainingSong': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlaylistsContainingSong,
                    request_deserializer=music__service__pb2.SongId.FromString,
                    response_serializer=music__service__pb2.PlaylistList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'music.MusicService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('music.MusicService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MusicService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.MusicService/GetUsers',
            music__service__pb2.Empty.SerializeToString,
            music__service__pb2.UserList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSongs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.MusicService/GetSongs',
            music__service__pb2.Empty.SerializeToString,
            music__service__pb2.SongList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlaylistsByUserId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.MusicService/GetPlaylistsByUserId',
            music__service__pb2.UserId.SerializeToString,
            music__service__pb2.PlaylistList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSongsFromPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.MusicService/GetSongsFromPlaylist',
            music__service__pb2.PlaylistId.SerializeToString,
            music__service__pb2.SongList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlaylistsContainingSong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.MusicService/GetPlaylistsContainingSong',
            music__service__pb2.SongId.SerializeToString,
            music__service__pb2.PlaylistList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
